apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.17.6
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: NAME
              value: api
            - name: LISTEN_ADDR
              value: 0.0.0.0:8081
          readinessProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
