---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.17.6
          ports:
            - containerPort: 9090
          env:
            - name: NAME
              value: "api"
            - name: MESSAGE
              value: "api running on k8s"
            - name: LISTEN_ADDR
              value: "0.0.0.0:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 9090
---
# todo: use  networking.k8s.io/v1
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 9090
